name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy website to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: "141.136.39.190"
          username: "u659359819.grilandeg.com"
          password: "Ostora609@"
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
            .vscode/**
            package.json
            package-lock.json
            tailwind.config.js
            scraping.py
            results.json
            scratch_main.js